### ISSUE TITLE
Compute node OOM while loading ch-benchmark data with 18 modified MVs

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#13060]
### Describe the bug

Run ch-benchmark modified queries except q3,q7,q8,q21 with 2800 warehouses. All the sources/MVs/sinks created successfully. The compute node OOM during loading data.

Namespace: ch-benchmark-pg-cdc-20231025-060139

https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/46#018b62a2-cbcb-4636-a4af-8a2f712ca336

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&from=1698213717228&to=1698218983113&var-datasource=P2453400D1763B4D9&var-namespace=ch-benchmark-pg-cdc-20231025-060139&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

<img width="1916" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/65aa5506-45e6-42bf-87b8-f5881fa014c9">

[1698214041-2023-10-25-06-07-20.auto.heap.gz](https://github.com/risingwavelabs/risingwave/files/13167329/1698214041-2023-10-25-06-07-20.auto.heap.gz)

Above is the first heap dump. Others are here https://s3.console.aws.amazon.com/s3/buckets/test-useast1-mgmt-bucket-archiver?region=us-east-1&prefix=k8s/ch-benchmark-pg-cdc-20231025-060139/benchmark-risingwave-compute-c-0/ccb93d72-e9cf-440f-9f21-485f1e21b8ae/2023-10-25/0/&showversions=false

### The version of RisingWave

nightly-20231024

**Comment by fuyufjh** [comment]
@wcy-fdu is working on Memtable spill. Hopefully it can solve this issue. If not, let's see later.

**Comment by fuyufjh** [comment]
`ENABLE_MEMORY_PROFILING` was true in last run. Let's analyze the heap dump to see what happened...

**Comment by wcy-fdu** [comment]
[1204-ch-benchmark-oom-cn-0.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13544041/1204-ch-benchmark-oom-cn-0.heap.collapsed.zip)


Cause by hash join executor, the JoinHashMap and try_flush together take up a lot of memory(1.7G)

**Comment by Little-Wallace** [comment]
Could we reduce parallel number for every mv when we create too many mv in one cluster? I think meta-service shall scale-in automatically.

**Comment by fuyufjh** [comment]
Ran again with memory-size-based back-pressure (#13775). Still OOMed... 🥹

[1701841399-2023-12-06-05-43-18.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13577722/1701841399-2023-12-06-05-43-18.auto.heap.collapsed.zip)

**Comment by fuyufjh** [comment]
> change the flush threshold to 1mb or smaller may work

I don't think so. Searching for `state_table`, the results show that the usage is less than 2GB, which is a reasonable number I think.

Besides, this part looks like memory usage of HashAgg. Still thinking about the reason.

<img width="1009" alt="Screenshot 2023-12-06 at 15 22 59" src="https://github.com/risingwavelabs/risingwave/assets/10192522/ec9cb70b-f37a-4b54-b23c-d8023636eef1">

**Comment by wcy-fdu** [comment]
> > change the flush threshold to 1mb or smaller may work
> 
> I don't think so. Searching for `state_table`, the results show that the usage is less than 2GB, which is a reasonable number I think.
> 
> Besides, this part looks like memory usage of HashAgg. Still thinking about the reason.
> 
> <img alt="Screenshot 2023-12-06 at 15 22 59" width="1009" src="https://private-user-images.githubusercontent.com/10192522/288324646-ec9cb70b-f37a-4b54-b23c-d8023636eef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDc4MTMsIm5iZiI6MTcwMTg0NzUxMywicGF0aCI6Ii8xMDE5MjUyMi8yODgzMjQ2NDYtZWM5Y2I3MGItZjM3YS00YjU0LWIyM2MtZDgwMjM2MzZlZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MjA2NzA2YmNmOGRiZjY0NDgwNDUxNjBhNWEwZTFmZmI5NDc5NzE0MWM5YjhmNTg1ODc4MzQyMGYyNjA5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqlLRa9qT2jlsriZOnwRZqw4vO5gzbBy8HyYGEZr9dM">

I see, so you suspect that what’s inside the red box above is some buffer? It is indeed difficult to analyze from the heap file.

**Comment by st1page** [comment]
> Besides, this part looks like memory usage of HashAgg. Still thinking about the reason.

1. parallelism amplification, Currently the memory based Agg emit is executor level. If a hashAgg Executor's dirty state is more than 64MB, it will emit these states. So the upper bound of the memory here is 64MB*32(parallelism) = 2GB.

- And 2-4 is anaylazing the flamegraph 
<img width="1673" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/d3ef1066-bd1c-430c-8b4d-10782fdeb943">

  2. there is some memory (515MB of 1956MB) can not be tracked by us currently and it is the memory used by HashMap self.

  3. We estimate the Key and value size in the hash map, but they are less than the memory in mem perf
      - value(`AggGroup::create`) consuming 352MB of 1956MB) 
      - key(`HashKey::deserialize`) consuming 544MB of 1956MB) 
    The expected estimated size should be 900MB but in metrics, RW only estimate 387MB. It could because the OOM comes too fast to report the metrics.
<img width="845" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/08cc81b0-ac0f-4e58-8dd4-f3d595d3e320">
  4. there still 544MB memory is allocating by hash agg but not in the dirty group

c.c. @stdrc

**Comment by fuyufjh** [comment]
Running a test with `stream_hash_agg_max_dirty_groups_heap_size` = 2MB

https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/104

I think it doesn't make sense that `stream_hash_agg_max_dirty_groups_heap_size` is much bigger than `mem_table_spill_threshold`. They should be same, right?

**Comment by st1page** [comment]
> Running a test with `stream_hash_agg_max_dirty_groups_heap_size` = 2MB
> 
> https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/104
> 
> I think it doesn't make sense that `stream_hash_agg_max_dirty_groups_heap_size` is much bigger than `mem_table_spill_threshold`. They should be same, right?

I guess Some AggGroup could be larger than the result row.

**Comment by fuyufjh** [comment]
> Running a test with `stream_hash_agg_max_dirty_groups_heap_size` = 2MB
> 
> https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/104
> 
> I think it doesn't make sense that `stream_hash_agg_max_dirty_groups_heap_size` is much bigger than `mem_table_spill_threshold`. They should be same, right?

The run didn't succeed, still OOMed. But the parameters did take some effect.

The memory usage of `HashAgg` (as pointed out with red box previously) disappeared.

[1701861649-2023-12-06-11-20-48.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13594613/1701861649-2023-12-06-11-20-48.auto.heap.collapsed.zip)

Now, nearly all memory is used by `state_table`.  

<img width="961" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/d131f877-a06a-4257-a8df-6f61c04e3e80">

I will continue looking into this. (Perhaps caused by some bad query plan? 🤔...)

@st1page I'd like to decrease the default `stream_hash_agg_max_dirty_groups_heap_size` to around 2MB. What do you think?

**Comment by fuyufjh** [comment]
Interesting observations on `stream_source_output_rows_counts` (total count, not `rate()`)

`stream_source_output_rows_counts` of `stock` table

<img width="1500" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/26ce3c91-2f7d-4870-b505-aceddce6413f">

`stream_source_output_rows_counts` of the rest tables

<img width="1497" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/36303e24-0701-4e63-8f20-b9f1d2db3297">

The rest tables didn't consume any changes until 19:20. And immediately after it starts, the compute node OOMed.

**Comment by cyliu0** [comment]
Running with 9 queries `q13,q14,q15,q16,q17,q18,q19,q20,q22` still got OOM 
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/106#018c4211-6622-4016-8188-dee2aabb8ca6

**Comment by fuyufjh** [comment]
There is a 140x amplification in Q20.

```sql
CREATE MATERIALIZED VIEW ch_benchmark_q20 AS
SELECT
    s_name,
    s_address
FROM
    supplier,
    nation
WHERE
    s_suppkey IN (
        SELECT
            mod(s_i_id * s_w_id, 10000)
        FROM
            stock,
            order_line
        WHERE
            s_i_id IN (
                SELECT
                    i_id
                FROM
                    item
                WHERE
                    i_data NOT LIKE 'co%'
            )
            AND ol_i_id = s_i_id
            AND ol_delivery_d > '2010-05-23 12:00:00'
        GROUP BY
            s_i_id,
            s_w_id,
            s_quantity
        HAVING
            200 * s_quantity > sum(ol_quantity)
    )
    AND s_nationkey = n_nationkey
```

Plan:

```
 StreamMaterialize { columns: [s_name, s_address, supplier.s_suppkey(hidden), supplier.s_nationkey(hidden)], stream_key: [supplier.s_suppkey, supplier.s_nationkey], pk_columns: [supplier.s_suppkey, supplier.s_nationkey], pk_conflict: NoCheck }
 └─StreamExchange { dist: HashShard(supplier.s_suppkey, supplier.s_nationkey) }
   └─StreamHashJoin { type: LeftSemi, predicate: supplier.s_suppkey = $expr1 }
     ├─StreamExchange { dist: HashShard(supplier.s_suppkey) }
     │ └─StreamHashJoin { type: Inner, predicate: supplier.s_nationkey = nation.n_nationkey }
     │   ├─StreamExchange { dist: HashShard(supplier.s_nationkey) }
     │   │ └─StreamTableScan { table: supplier, columns: [s_suppkey, s_name, s_address, s_nationkey] }
     │   └─StreamExchange { dist: HashShard(nation.n_nationkey) }
     │     └─StreamTableScan { table: nation, columns: [n_nationkey] }
     └─StreamExchange { dist: HashShard($expr1) }
       └─StreamProject { exprs: [((stock.s_i_id * stock.s_w_id) % 10000:Int32)::Int64 as $expr1, stock.s_i_id, stock.s_w_id, stock.s_quantity] }
         └─StreamFilter { predicate: ((200:Int32 * stock.s_quantity) > sum(order_line.ol_quantity)) }
           └─StreamProject { exprs: [stock.s_i_id, stock.s_w_id, stock.s_quantity, sum(order_line.ol_quantity)] }
             └─StreamHashAgg { group_key: [stock.s_i_id, stock.s_w_id, stock.s_quantity], aggs: [sum(order_line.ol_quantity), count] }
               └─StreamHashJoin { type: LeftSemi, predicate: stock.s_i_id = item.i_id } 
                 ├─StreamHashJoin { type: Inner, predicate: stock.s_i_id = order_line.ol_i_id } ❗️❗️❗️ 
                 │ ├─StreamExchange { dist: HashShard(stock.s_i_id) }
                 │ │ └─StreamTableScan { table: stock, columns: [s_i_id, s_w_id, s_quantity] }
                 │ └─StreamExchange { dist: HashShard(order_line.ol_i_id) }
                 │   └─StreamProject { exprs: [order_line.ol_i_id, order_line.ol_quantity, order_line.ol_w_id, order_line.ol_d_id, order_line.ol_o_id, order_line.ol_number] }
                 │     └─StreamFilter { predicate: (order_line.ol_delivery_d > '2010-05-23 12:00:00':Timestamp) }
                 │       └─StreamTableScan { table: order_line, columns: [ol_i_id, ol_quantity, ol_w_id, ol_d_id, ol_o_id, ol_number, ol_delivery_d] }
                 └─StreamExchange { dist: HashShard(item.i_id) }
                   └─StreamProject { exprs: [item.i_id] }
                     └─StreamFilter { predicate: Not(Like(item.i_data, 'co%':Varchar)) }
                       └─StreamTableScan { table: item, columns: [i_id, i_data] }
```

Notice the `StreamHashJoin` with `❗️❗️❗️`, the join condition is `stock.s_i_id = order_line.ol_i_id`

However, the stock table is very large (around 14,000,000 rows), but with only 100,000 distinct value of `s_i_id`, so each new line in `order_line` will be amplified 140x

<img width="575" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/698a69b1-ed98-480a-a7ac-6b7360e8259a">

<img width="358" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/237d9e8d-75ff-49d1-a1ab-cbada332b68d">

**Comment by lmatz** [comment]
> so each new line in order_line will be amplified 1400x

Is big amplification supposed to be solved by spill anytime https://github.com/risingwavelabs/risingwave/pull/12028?

**Comment by fuyufjh** [comment]
> > so each new line in order_line will be amplified 1400x
> 
> Is big amplification supposed to be solved by spill anytime #12028?

Partially. The big amplification may cause multiple problems. Even regarding of OOM, there are more than one problem. But AFAIK the major one is caused by memtable, thus, can be solved by spill anytime.

**Comment by lmatz** [comment]
let me run the same setting again with `nightly-20240102`:
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/150#018cd321-b085-4136-ac9c-4327b8feb534

**Comment by lmatz** [comment]
It OOMed:
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/150#018cd321-b085-4136-ac9c-4327b8feb534

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&from=1704349538555&to=1704350593203&var-datasource=P2453400D1763B4D9&var-namespace=ch-benchmark-pg-cdc-20240104-062245&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All
![SCR-20240104-ksk](https://github.com/risingwavelabs/risingwave/assets/5791930/340ba796-5a6b-4c1d-a6c3-7706241a1ba1)


However, I didn't find the heap dumps on s3 while the other two executions of the same pipeline do exist.


![SCR-20240104-knl](https://github.com/risingwavelabs/risingwave/assets/5791930/c7252b45-b743-47cc-96cd-43a084696212)
![SCR-20240104-knz](https://github.com/risingwavelabs/risingwave/assets/5791930/bcc995d1-a083-4a0d-807d-f27b6382de96)
![SCR-20240104-kux](https://github.com/risingwavelabs/risingwave/assets/5791930/97e45c76-c4f7-4cc0-9ac0-d99e6cd4408f)

All 3CNs OOMed at the same time.

**Comment by fuyufjh** [comment]
> However, I didn't find the heap dumps on s3 while the other two executions of the same pipeline today do exist.

You probably need:

```
ENABLE_MEMORY_PROFILING="true"
```

This is sometimes annoying...

**Comment by lmatz** [comment]
let me make it true as default because we no long do sampling anymore.


And the entire machine's memory is enough for the workload:
https://grafana.test.risingwave-cloud.xyz/d/LDL_mx9nz123/kubernetes-node-exporter?orgId=1&var-DS_PROMETHEUS=P2453400D1763B4D9&var-node=ip-10-0-41-244.ec2.internal&var-internal_ip=10.0.41.244&var-diskdevices=%5Ba-z%5D+%7Cnvme%5B0-9%5D+n%5B0-9%5D+%7Cmmcblk%5B0-9%5D+&from=1704346828944&to=1704352403138

![SCR-20240104-l5g](https://github.com/risingwavelabs/risingwave/assets/5791930/bfb77d0d-a4b2-4ad3-964d-9e31b7923b0c)

**Comment by lmatz** [comment]
The memory usage of the 3 CNs look similar to the one in https://github.com/risingwavelabs/risingwave/issues/14251

**Comment by lmatz** [comment]
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/152#018cd34b-eaf3-4148-a74c-4da996384253:

![SCR-20240104-lxr](https://github.com/risingwavelabs/risingwave/assets/5791930/9b08f380-5443-430c-9e3a-c33cc201e8e9)
![SCR-20240104-ly3](https://github.com/risingwavelabs/risingwave/assets/5791930/01583715-bbc1-44e5-9731-44a44a32abf0)
[collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13827468/collapsed.zip)
![SCR-20240104-ly9](https://github.com/risingwavelabs/risingwave/assets/5791930/c5dd8989-4e6d-4218-b6ec-9aabd89af4b2)

**Comment by fuyufjh** [comment]
I just analyzed [Run 149](https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/149#018cd318-8708-418b-a709-ef40908c401d) (namespace: `ch-benchmark-pg-cdc-20240104-061254`) and the conclusion is same as above. The prost message decoding used more than 6GB memory. 
[1704349111-2024-01-04-06-18-30.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13827544/1704349111-2024-01-04-06-18-30.auto.heap.collapsed.zip)

**Comment by st1page** [comment]
<img width="1009" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/a2d6b9f2-c606-4bb6-b137-4f50de816206">

the message of the `BarrierMutation` consume 6GB

**Comment by st1page** [comment]
<img width="777" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/40830455/8369ca75-1b8d-485a-8b21-3fded67475e4">

```
message AddMutation {
  // New dispatchers for each actor.
  map<uint32, Dispatchers> actor_dispatchers = 1;
  // All actors to be added (to the main connected component of the graph) in this update.
  repeated uint32 added_actors = 3;
  // We may embed a source change split mutation here.
  // TODO: we may allow multiple mutations in a single barrier.
  map<uint32, source.ConnectorSplits> actor_splits = 2;
  // We may embed a pause mutation here.
  // TODO: we may allow multiple mutations in a single barrier.
  bool pause = 4;
}

message Dispatchers {
  repeated Dispatcher dispatchers = 1;
}

message Dispatcher {
  DispatcherType type = 1;
  // Indices of the columns to be used for hashing.
  // For dispatcher types other than HASH, this is ignored.
  repeated uint32 dist_key_indices = 2;
  // Indices of the columns to output.
  // In most cases, this contains all columns in the input. But for some cases like MV on MV or
  // schema change, we may only output a subset of the columns.
  repeated uint32 output_indices = 6;
  // The hash mapping for consistent hash.
  // For dispatcher types other than HASH, this is ignored.
  ActorMapping hash_mapping = 3;
  // Dispatcher can be uniquely identified by a combination of actor id and dispatcher id.
  // This is exactly the same as its downstream fragment id.
  uint64 dispatcher_id = 4;
  // Number of downstreams decides how many endpoints a dispatcher should dispatch.
  repeated uint32 downstream_actor_id = 5;
}

```

```
std::mem::size_of::<risingwave_pb::stream_plan::Dispatcher>() = 136
```

parallelism is 96 and there are only 3CN? 
there will be 96/3 = 32  AddMutation messages in each CN.
each AddMutation message will have totall actors number elements in the hashMap `actor_dispatchers` which is 96(paralellism)*10(fragment num)
each Dispatchers will have 96 elements.
136Byte * 96 * 96 * 10 * 32  = 382.5MB 
there is still about 10x amplification in somewhere. 
Is there any case that there can be more than one DDL in the pipeline?

**Comment by lmatz** [comment]
> there is still about 10x amplification in somewhere.
Is there any case that there can be more than one DDL in the pipeline?

This is a direct CDC testing pipeline, does it matter?

also cc: @cyliu0 for the  DDL question

**Comment by st1page** [comment]
> parallelism is 96 and there are only 3CN?
> there will be 96/3 = 32 AddMutation messages in each CN.
> each AddMutation message will have totall actors number elements in the hashMap `actor_dispatchers` which is 96(paralellism)*10(fragment num)
> each Dispatchers will have 96 elements(Dispatcher).
> 136Byte * 96 * 96 * 10 * 32 = 382.5MB
> there is still about 10x amplification in somewhere.
> Is there any case that there can be more than one DDL running concurrently in the pipeline?

Oh there are 12 tables in the ch benchmark so 

> there will be 96/3 = 32 AddMutation messages in each CN.

should be 12(sources num) * 96 (total parallelism) / 3 (CN num)
And then the memory consumption is 382.5MB * 12 = 4590MB which makes sense with the memory heap number

**Comment by yezizp2012** [comment]
Note that the barrier will be passed via PRC acrossing actors that are located in different compute nodes.

`barrier_total_size = local_actor_number * upstream_remote_actor_number * barrier_size`

For Q1 and Q2, the result is like:

`6G = 32 * (32 * 2 * ( 8(base tables) + 1(q1) + 17(q2) + 11 (connection between base table and q1,q2)) * barrier_size`

The `barrier_size` would be like 83k.

**Comment by st1page** [comment]
> Note that the barrier will be passed via PRC acrossing actors that are located in different compute nodes.
> 
> `barrier_total_size = local_actor_number * upstream_remote_actor_number * barrier_size`
> 
> For Q1 and Q2, the result is like:
> 
> `6G = 32 * (32 * 2 * ( 8(base tables) + 1(q1) + 17(q2) + 11 (connection between base table and q1,q2)) * barrier_size`
> 
> The `barrier_size` would be around 83k.

So the worst case happens in the exchange and there could be 32 * (96-32) barrier exists concurrently for the same exchange :exploding_head:

**Comment by yezizp2012** [comment]
> So the worst case happens in the exchange and there could be 32 * (96-32) barrier exists concurrently for the same exchange 🤯

Yes exactly. 🥵

**Comment by yezizp2012** [comment]
Some thoughts discussed with @st1page , there is one feasible optimization solution to change the process of the barrier:
Before sending the barrier, it can be sent to the local barrier manager on compute node first. When injecting the barrier, only bring along the id (`epoch`). After receiving the barrier, if actor needs to read specific mutation information, it can fetch it from the local barrier manager. This way, `BarrierMutation` only needs to be decoded once on each compute node.

**Comment by cyliu0** [comment]
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/154#018cd481-11b2-43a9-ad14-117115a7a039 

3CN with 8 CPUs also OOM

```
[benchmark.risingwave.cpu.resources.compute]
limit = 8
request = 7
```

**Comment by fuyufjh** [comment]
Still on going: https://risingwave-labs.slack.com/archives/C041S66NCJU/p1704791216717479?thread_ts=1704352295.846119&cid=C041S66NCJU

**Comment by cyliu0** [comment]
Tested 18 MVs with v1.7.0-rc-1 and 140 warehouses. No OOM happened. https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/201#018d7879-4a9a-4aaf-81db-fbfc84b7ad24

**Comment by lmatz** [comment]
I suppose right now the daily test only runs q1~q12 instead of all the ch-benchmark queries to keep RW from out-of-memory? @cyliu0

**Comment by cyliu0** [comment]
> I suppose right now the daily test only runs q1~q12 instead of all the ch-benchmark queries to keep RW from out-of-memory? @cyliu0

Yes. And we removed query q3 as well. Because it will hit https://github.com/risingwavelabs/risingwave/issues/14943

**Comment by fuyufjh** [comment]
> Still on going: https://risingwave-labs.slack.com/archives/C041S66NCJU/p1704791216717479?thread_ts=1704352295.846119&cid=C041S66NCJU

The issue was caused by too high parallelism. Fixed now.

**Comment by lmatz** [comment]
Since it is fixed, can we bring back the test as a daily test? @cyliu0

**Comment by cyliu0** [comment]
The q3 problem https://github.com/risingwavelabs/risingwave/issues/14943 is still there. And some queries between q13-q22 still have the same problem as q3. I'll test them one by one and add the passed one back to daily test

**Comment by lmatz** [comment]
> The q3 problem #14943 is still there. And some queries between q13-q22 still have the same problem as q3. I'll test them one by one and add the passed one back to daily test

Is #14943 also OOM? looks like a different problem

**Comment by cyliu0** [comment]
> Is #14943 also OOM? looks like a different problem

No. But it will also lead to test fail
