### ISSUE TITLE
bug: `BindContext` and `bind_column` does not support schema-qualified names

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#5176]
### Describe the bug

The definition of `BindContext` only have 2 levels: table name and column name. As a result, when `bind_column` sees `public.a.id` or `tmp.a.id`, the schema part is ignored.

### To Reproduce

```
create schema tmp;
create table public.a(id int, a int);
create table tmp.a(id int, b int);
select a, b from public.a join tmp.a on public.a.id = tmp.a.id;
```

Actual run reports an error:
```
Duplicated table name while binding table to context: a
```

Thanks @HuaHuaY for reporting

### Expected behavior

```
 a | b 
---+---
(0 rows)
```

### Additional context

Note that PostgreSQL does have this `table name "a" specified more than once` error for CTE:
```
with a(id, c) as (select 1, 2) select b, c from tmp.a.id join a on tmp.a.id = a.id;
```

Need to take a deeper look at when duplicates are allowed and when not.

**Comment by HuaHuaY** [comment]
Add a case.
```sql
create schema tmp;
create table public.a(id int, a int);
create table tmp.a(id int, b int);
select a, b from a join tmp.a on a.id = tmp.a.id;
```
PostgreSQL will report an error:
```
ERROR:  table reference "a" is ambiguous
LINE 1: select a, b from a join tmp.a on a.id = tmp.a.id;
                                         ^
```

**Comment by Standing-Man** [comment]
Fix CTE SQL on the additional context:

`with a(id, c) as (select 1, 2) select b, c from tmp.a join a on tmp.a.id = a.id;`

**Comment by hzxa21** [comment]
@Standing-Man is this fixed by #24628. Feel free to close this issue.

**Comment by Standing-Man** [comment]
> [@Standing-Man](https://github.com/Standing-Man) is this fixed by [#24628](https://github.com/risingwavelabs/risingwave/pull/24628). Feel free to close this issue.

Hi @hzxa21, This issue is not fully resolved yet. I will address the remaining problems in a future PR.
