### ISSUE TITLE
bug(frontend): input references are inconsistent with input schema

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7501]
### Describe the bug

> thread 'risingwave-main' panicked at 'Input references are inconsistent with the input schema: InputRef#0 has type smallint, but its type is timestamp without time zone in the input schema.

```
thread 'risingwave-main' panicked at 'Input references are inconsistent with the input schema: InputRef#0 has type smallint, but its type is timestamp without time zone in the input schema, plan:
LogicalProject { exprs: [1:Int32] }
└─LogicalJoin { type: LeftSemi, on: IsNotDistinctFrom(m3.col_0, m3.col_0) AND IsNotDistinctFrom(m3.col_1, m3.col_1) AND IsNotDistinctFrom(alltypes1.c3, alltypes1.c3) AND IsNotDistinctFrom(alltypes1.c13, alltypes1.c13) }
  ├─LogicalJoin { type: Inner, on: true }
  | ├─LogicalScan { table: m3, columns: [col_0, col_1] }
  | └─LogicalScan { table: alltypes1, columns: [c3, c13] }
  └─LogicalJoin { type: LeftSemi, on: IsNotDistinctFrom(person.date_time, alltypes1.c13) AND IsNotDistinctFrom(m3.col_0, person.date_time) AND IsNotDistinctFrom(m3.col_1, m3.col_0) AND IsNotDistinctFrom(alltypes1.c3, m3.col_1) AND IsNotDistinctFrom(alltypes1.c13, alltypes1.c3) }
    ├─LogicalJoin { type: Inner, on: true }
    | ├─LogicalJoin { type: Inner, on: true }
    | | ├─LogicalAgg { group_key: [m3.col_0, m3.col_1, alltypes1.c3, alltypes1.c13], aggs: [] }
    | | | └─LogicalJoin { type: Inner, on: true }
    | | |   ├─LogicalScan { table: m3, columns: [col_0, col_1] }
    | | |   └─LogicalScan { table: alltypes1, columns: [c3, c13] }
    | | └─LogicalScan { table: region, columns: [] }
    | └─LogicalScan { table: person, columns: [date_time] }
    └─LogicalProject { exprs: [person.date_time, m3.col_0, m3.col_1, alltypes1.c3, alltypes1.c13] }
      └─LogicalAgg { group_key: [person.date_time, m3.col_0, m3.col_1, alltypes1.c3, alltypes1.c13, alltypes1.c13], aggs: [] }
        └─LogicalJoin { type: Inner, on: true }
          ├─LogicalAgg { group_key: [person.date_time], aggs: [] }
          | └─LogicalScan { table: person, columns: [date_time] }
          └─LogicalJoin { type: LeftOuter, on: (bid.channel = orders.o_orderpriority) }
            ├─LogicalJoin { type: Inner, on: true }
            | ├─LogicalAgg { group_key: [m3.col_0, m3.col_1, alltypes1.c3, alltypes1.c13], aggs: [] }
            | | └─LogicalJoin { type: Inner, on: true }
            | |   ├─LogicalScan { table: m3, columns: [col_0, col_1], predicate: (1902202048.6001704:Decimal < m3.col_1) }
            | |   └─LogicalScan { table: alltypes1, columns: [c3, c13] }
            | └─LogicalScan { table: bid, columns: [channel] }
            └─LogicalScan { table: orders, columns: [o_orderpriority] }
', src/frontend/src/optimizer/mod.rs:432:27
```

### To Reproduce

`ddl`
```sql
CREATE TABLE supplier (s_suppkey INT, s_name CHARACTER VARYING, s_address CHARACTER VARYING, s_nationkey INT, s_phone CHARACTER VARYING, s_acctbal NUMERIC, s_comment CHARACTER VARYING, PRIMARY KEY (s_suppkey));CREATE TABLE part (p_partkey INT, p_name CHARACTER VARYING, p_mfgr CHARACTER VARYING, p_brand CHARACTER VARYING, p_type CHARACTER VARYING, p_size INT, p_container CHARACTER VARYING, p_retailprice NUMERIC, p_comment CHARACTER VARYING, PRIMARY KEY (p_partkey));CREATE TABLE partsupp (ps_partkey INT, ps_suppkey INT, ps_availqty INT, ps_supplycost NUMERIC, ps_comment CHARACTER VARYING, PRIMARY KEY (ps_partkey, ps_suppkey));CREATE TABLE customer (c_custkey INT, c_name CHARACTER VARYING, c_address CHARACTER VARYING, c_nationkey INT, c_phone CHARACTER VARYING, c_acctbal NUMERIC, c_mktsegment CHARACTER VARYING, c_comment CHARACTER VARYING, PRIMARY KEY (c_custkey));CREATE TABLE orders (o_orderkey BIGINT, o_custkey INT, o_orderstatus CHARACTER VARYING, o_totalprice NUMERIC, o_orderdate DATE, o_orderpriority CHARACTER VARYING, o_clerk CHARACTER VARYING, o_shippriority INT, o_comment CHARACTER VARYING, PRIMARY KEY (o_orderkey));CREATE TABLE lineitem (l_orderkey BIGINT, l_partkey INT, l_suppkey INT, l_linenumber INT, l_quantity NUMERIC, l_extendedprice NUMERIC, l_discount NUMERIC, l_tax NUMERIC, l_returnflag CHARACTER VARYING, l_linestatus CHARACTER VARYING, l_shipdate DATE, l_commitdate DATE, l_receiptdate DATE, l_shipinstruct CHARACTER VARYING, l_shipmode CHARACTER VARYING, l_comment CHARACTER VARYING, PRIMARY KEY (l_orderkey, l_linenumber));CREATE TABLE nation (n_nationkey INT, n_name CHARACTER VARYING, n_regionkey INT, n_comment CHARACTER VARYING, PRIMARY KEY (n_nationkey));CREATE TABLE region (r_regionkey INT, r_name CHARACTER VARYING, r_comment CHARACTER VARYING, PRIMARY KEY (r_regionkey));CREATE TABLE person (id BIGINT, name CHARACTER VARYING, email_address CHARACTER VARYING, credit_card CHARACTER VARYING, city CHARACTER VARYING, state CHARACTER VARYING, date_time TIMESTAMP, extra CHARACTER VARYING, PRIMARY KEY (id));CREATE TABLE auction (id BIGINT, item_name CHARACTER VARYING, description CHARACTER VARYING, initial_bid BIGINT, reserve BIGINT, date_time TIMESTAMP, expires TIMESTAMP, seller BIGINT, category BIGINT, extra CHARACTER VARYING, PRIMARY KEY (id));CREATE TABLE bid (auction BIGINT, bidder BIGINT, price BIGINT, channel CHARACTER VARYING, url CHARACTER VARYING, date_time TIMESTAMP, extra CHARACTER VARYING);CREATE TABLE alltypes1 (c1 BOOLEAN, c2 SMALLINT, c3 INT, c4 BIGINT, c5 REAL, c6 DOUBLE, c7 NUMERIC, c8 DATE, c9 CHARACTER VARYING, c10 TIME, c11 TIMESTAMP, c13 INTERVAL, c14 STRUCT<a INT>, c15 INT[], c16 CHARACTER VARYING[]);CREATE TABLE alltypes2 (c1 BOOLEAN, c2 SMALLINT, c3 INT, c4 BIGINT, c5 REAL, c6 DOUBLE, c7 NUMERIC, c8 DATE, c9 CHARACTER VARYING, c10 TIME, c11 TIMESTAMP, c13 INTERVAL, c14 STRUCT<a INT>, c15 INT[], c16 CHARACTER VARYING[]);CREATE MATERIALIZED VIEW m0 AS WITH with_0 AS (WITH with_1 AS (SELECT INT '0' # INT '1066101944' AS col_0, REAL '0' AS col_1, 0 AS col_2, NULL AS col_3 FROM alltypes2 AS t_2 GROUP BY t_2.c13, t_2.c16, t_2.c7, t_2.c15 HAVING FLOAT '0' <> SMALLINT '6523') SELECT 9223372036854775807 AS col_0 FROM with_1 WHERE false) SELECT DATE '2023-01-12' AS col_0, SMALLINT '32767' AS col_1, DATE '2023-01-19' AS col_2, INT '1' - SMALLINT '16200' AS col_3 FROM with_0;CREATE MATERIALIZED VIEW m2 AS SELECT t_0.price AS col_0 FROM bid AS t_0 WHERE false GROUP BY t_0.url, t_0.bidder, t_0.price HAVING TIME '18:13:37' <= INTERVAL '60';CREATE MATERIALIZED VIEW m3 AS SELECT SMALLINT '7847' % SMALLINT '7505' AS col_0, REAL '1769111741.4546845' / (REAL '779339109.7915436' * (avg(t_0.c6) - ((REAL '0' + REAL '1526321202.4274392') * (- sum(t_0.c5))))) AS col_1 FROM alltypes1 AS t_0 WHERE false GROUP BY t_0.c7, t_0.c9, t_0.c15 HAVING INT '779491282' = t_0.c7;CREATE MATERIALIZED VIEW m4 AS SELECT TIMESTAMP '2023-01-18 23:34:18' AS col_0, SMALLINT '2843' / (SMALLINT '32767' << SMALLINT '1') AS col_1, SMALLINT '23585' AS col_2 FROM m2 AS t_0 WHERE false GROUP BY t_0.col_0 HAVING false;CREATE MATERIALIZED VIEW m5 AS SELECT TIMESTAMP '2023-01-19 00:33:18' AS col_0, INT '1' << SMALLINT '6699' AS col_1, NULL AS col_2, false AS col_3 FROM bid AS t_0 WHERE true GROUP BY t_0.bidder, t_0.extra, t_0.auction;CREATE MATERIALIZED VIEW m6 AS SELECT (DATE '2023-01-18' - INT '2147483647') - (INT '355929804' + SMALLINT '0') AS col_0, REAL '861863074.2795333' AS col_1 FROM alltypes2 AS t_0 WHERE t_0.c1 GROUP BY t_0.c5;CREATE MATERIALIZED VIEW m7 AS SELECT FLOAT '0' * REAL '2031721016.7714844' AS col_0, INTERVAL '604800' AS col_1, t_0.col_1 AS col_2, TIMESTAMP '2023-01-12 00:34:18' AS col_3 FROM m0 AS t_0 WHERE true GROUP BY t_0.col_2, t_0.col_3, t_0.col_1, t_0.col_0;CREATE MATERIALIZED VIEW m8 AS SELECT INT '1' AS col_0, TIMESTAMP '2023-01-18 23:34:18' AS col_1, ARRAY[FLOAT '1799608149.304795', FLOAT '2147483647', FLOAT '1', FLOAT '1035908998.5570484', FLOAT '1', FLOAT '0', FLOAT '2147483647', FLOAT '732702462.94929', FLOAT '75175162.29377627', FLOAT '1', FLOAT '2147483647', FLOAT '2147483647', FLOAT '1067564325.3872435', FLOAT '1098073362.4269292', FLOAT '946090710.8442223', FLOAT '2147483647', FLOAT '2147483647', FLOAT '1768280412.62701', FLOAT '1', FLOAT '2147483647', FLOAT '1', FLOAT '1', FLOAT '1163083131.3457673', FLOAT '1720357832.98174', FLOAT '1', FLOAT '0', FLOAT '1', FLOAT '1', FLOAT '1', FLOAT '0', FLOAT '0', FLOAT '1', FLOAT '0', FLOAT '894453204.4768381', FLOAT '2147483647', FLOAT '1', FLOAT '2147483647', FLOAT '1'] AS col_2 FROM region AS t_0 GROUP BY t_0.r_comment HAVING CAST(INT '1' AS BOOLEAN);CREATE MATERIALIZED VIEW m9 AS SELECT REAL '1997584262.644123' AS col_0, FLOAT '2147483647' AS col_1, t_0.o_totalprice AS col_2 FROM orders AS t_0 GROUP BY t_0.o_totalprice, t_0.o_orderpriority, t_0.o_orderdate, t_0.o_clerk, t_0.o_custkey, t_0.o_orderstatus, t_0.o_shippriority, t_0.o_comment;
```

`query`
```sql
SELECT 
  1 AS col_0 
FROM 
  m3 AS t_12, 
  alltypes1 AS t_15 
WHERE 
  EXISTS (
    SELECT 
      (t_12.col_0 | t_12.col_0) >> t_15.c3 AS col_0 
    FROM 
      region AS t_18, 
      person AS t_25 
    WHERE 
      EXISTS (
        SELECT 
          DATE '2023-01-19' AS col_0, 
          t_15.c13 AS col_1, 
          REAL '494396435.4060445' = 2007668285.504539 AS col_2, 
          'FSbuRfGfpY' AS col_3 
        FROM 
          bid AS t_38 
          LEFT JOIN orders AS t_39 ON t_38.channel = t_39.o_orderpriority 
        WHERE 
          1902202048.6001704 < t_12.col_1 
        GROUP BY 
          t_25.date_time
      )
  );

```

### Additional context

Related to https://github.com/risingwavelabs/risingwave/issues/7473. Found when I was shrinking the query further.

**Comment by jon-chuang** [comment]
The bug is caused by general query unnesting:

```rust
        // General Unnesting.
        // Translate Apply, push Apply down the plan and finally replace Apply with regular inner
        // join.
        plan = self.optimize_by_rules(
            plan,
            "General Unnesting(Translate Apply)".to_string(),
            vec![TranslateApplyRule::create()],
            ApplyOrder::BottomUp,
        );
        plan = self.optimize_by_rules_until_fix_point(
            plan,
            "General Unnesting(Push Down Apply)".to_string(),
            vec![
                ApplyAggTransposeRule::create(),
                ApplyFilterTransposeRule::create(),
                ApplyProjectTransposeRule::create(),
                ApplyJoinTransposeRule::create(),
                ApplyShareEliminateRule::create(),
                ApplyScanRule::create(),
            ],
            ApplyOrder::TopDown,
        );
        if has_logical_apply(plan.clone()) {
            return Err(ErrorCode::InternalError("Subquery can not be unnested.".into()).into());
        }


        #[cfg(debug_assertions)]
        InputRefValidator.validate(plan.clone());
```

**Comment by kwannoel** [comment]
Fixed in #7507

**Comment by jon-chuang** [comment]
Seems not fully fixed? https://github.com/risingwavelabs/risingwave/issues/7473
